from pathlib import Path

this = Path(__file__).parent

ArmyRose_7 = this.joinpath('ArmyRose_7.png').absolute().as_posix()
ArmyRose_5 = this.joinpath('ArmyRose_5.png').absolute().as_posix()
Geyser_7 = this.joinpath('Geyser_7.png').absolute().as_posix()
Geyser_5 = this.joinpath('Geyser_5.png').absolute().as_posix()
TealRose_7 = this.joinpath('TealRose_7.png').absolute().as_posix()
TealRose_5 = this.joinpath('TealRose_5.png').absolute().as_posix()
Tropic_7 = this.joinpath('Tropic_7.png').absolute().as_posix()
Tropic_5 = this.joinpath('Tropic_5.png').absolute().as_posix()
Balance_7 = this.joinpath('Balance_7.png').absolute().as_posix()
Balance_5 = this.joinpath('Balance_5.png').absolute().as_posix()
Curl_7 = this.joinpath('Curl_7.png').absolute().as_posix()
Curl_5 = this.joinpath('Curl_5.png').absolute().as_posix()
Delta_7 = this.joinpath('Delta_7.png').absolute().as_posix()
Delta_5 = this.joinpath('Delta_5.png').absolute().as_posix()
BrBG_7 = this.joinpath('BrBG_7.png').absolute().as_posix()
BrBG_5 = this.joinpath('BrBG_5.png').absolute().as_posix()
PiYG_7 = this.joinpath('PiYG_7.png').absolute().as_posix()
PiYG_5 = this.joinpath('PiYG_5.png').absolute().as_posix()
PRGn_7 = this.joinpath('PRGn_7.png').absolute().as_posix()
PRGn_5 = this.joinpath('PRGn_5.png').absolute().as_posix()
PuOr_7 = this.joinpath('PuOr_7.png').absolute().as_posix()
PuOr_5 = this.joinpath('PuOr_5.png').absolute().as_posix()
RdBu_7 = this.joinpath('RdBu_7.png').absolute().as_posix()
RdBu_5 = this.joinpath('RdBu_5.png').absolute().as_posix()
RdGy_7 = this.joinpath('RdGy_7.png').absolute().as_posix()
RdGy_5 = this.joinpath('RdGy_5.png').absolute().as_posix()
RdYlBu = this.joinpath('RdYlBu.png').absolute().as_posix()
RdYlGn = this.joinpath('RdYlGn.png').absolute().as_posix()
Spectral = this.joinpath('Spectral.png').absolute().as_posix()
coolwarm = this.joinpath('coolwarm.png').absolute().as_posix()


husl = this.joinpath('husl.png').absolute().as_posix()
hls = this.joinpath('hls.png').absolute().as_posix()
tab20 = this.joinpath('tab20.png').absolute().as_posix()
tab20b = this.joinpath('tab20b.png').absolute().as_posix()
tab20c = this.joinpath('tab20c.png').absolute().as_posix()
Paired = this.joinpath('Paired.png').absolute().as_posix()
Set3 = this.joinpath('Set3.png').absolute().as_posix()
deep = this.joinpath('deep.png').absolute().as_posix()
muted = this.joinpath('muted.png').absolute().as_posix()
bright = this.joinpath('bright.png').absolute().as_posix()
pastel = this.joinpath('pastel.png').absolute().as_posix()
dark = this.joinpath('dark.png').absolute().as_posix()
colorblind = this.joinpath('colorblind.png').absolute().as_posix()
tab10 = this.joinpath('tab10.png').absolute().as_posix()
Pastel1 = this.joinpath('Pastel1.png').absolute().as_posix()
Set1 = this.joinpath('Set1.png').absolute().as_posix()
Pastel2 = this.joinpath('Pastel2.png').absolute().as_posix()
Accent = this.joinpath('Accent.png').absolute().as_posix()
Dark2 = this.joinpath('Dark2.png').absolute().as_posix()
Set2 = this.joinpath('Set2.png').absolute().as_posix()

result_file_icon = this.joinpath('result_files.svg').absolute().as_posix()
bar_plot_icon = this.joinpath('bar_plot.svg').absolute().as_posix()
line_plot_icon = this.joinpath('line_plot.svg').absolute().as_posix()
heatmap_plot_icon = this.joinpath('heatmap_plot.svg').absolute().as_posix()
pymol_icon = this.joinpath('pymol_icon.svg').absolute().as_posix()
result_table_icon = this.joinpath('result_table.svg').absolute().as_posix()
restore_icon = this.joinpath('restore.svg').absolute().as_posix()
save_default_config = this.joinpath('save_default_config.svg').absolute().as_posix()
default_config = this.joinpath('default_config.svg').absolute().as_posix()
save_user_config = this.joinpath('save_user_config.svg').absolute().as_posix()
user_config = this.joinpath('user_config.svg').absolute().as_posix()
alert = this.joinpath('alert.svg').absolute().as_posix()
config = this.joinpath('cog.svg').absolute().as_posix()

toc_img = this.joinpath('TOC.png').absolute().as_posix()
logo = this.joinpath('logo.svg').absolute().as_posix()
colors_icons = [ArmyRose_7, ArmyRose_5, Geyser_7, Geyser_5]
